### ISSUE TITLE
添加许多重复的路由的代价

### ISSUE THREAD

**Issue by zack24q** [ElderJames/vue-router-storage#11]
举个例子：
这个库每次进入应用或刷新时会将`LocalStorage`存储的所有路由`pushState`一遍，如果用户从搜索引擎进入应用，并在使用的过程中多刷新了几遍，那么就会添加很多重复的路由到浏览器中。这样的代价就是：
- 如果路由到达根目录时限制用户继续后退，用户就无法返回到搜索引擎页面；
- 如果不限制，那么用户需要将之前的路由再重新返回完才能返回到搜索引擎页面。并且在chrome中，history最大长度为50，满了后再添加新的路由会将之前的历史记录清除掉，所以用户可能再也无法返回到搜索引擎页。

所以带来的最大问题就是用户进入该应用后无法方便的返回，并且破坏了用户的浏览记录，这可能会让用户很费解，“我只是刷新了几下，但是我的历史记录里就全部都是这个单页应用的地址了”。浏览器的历史记录里应该存放有对用户有意义的路由，希望以后浏览器能有更好的方案来让开发者安全地操作历史记录，从而方便用户的使用。

另一个问题就是当历史记录比较多时，刷新后白屏的事件比较长，因为`history.pushState`并没有那么快。

另外建议**这个库的初始化尽量不要放在组件的钩子里做**。`mixin`会将代码混合到所有组件中，如果写得不好，很容易产生性能问题。

当然这要看具体的使用场景，但是作为开源的库的话，最好还是能覆盖尽可能多的使用场景，并且不破坏规范，期待能找到更好的方案。

**Comment by ElderJames** [comment]
对于初始化，这个插件需要用到router实例，所以如果不在钩子里取，还可以在哪里取得到呢？

我看了你的插件的方案，是直接传入router实例的，会不会不太灵活？

**Comment by zack24q** [comment]
mixin中应该放那些每个组件都要执行的代码，而不是库的初始化，虽然加了判断能够让初始化代码只执行一遍，但是代码应该不是只完成功能就算完成了的，还可以继续优化。初始化放在外面更好，逻辑更清楚，不容易出错，对组件的侵入性更小，并且初始化操作执行的时机更早。

官方的[vuex-router-sync](https://github.com/vuejs/vuex-router-sync)库的初始化也是手动传入实例，可以参考下。

**Comment by zack24q** [comment]
可以看一下这个官方教程的[全局混合](https://cn.vuejs.org/v2/guide/mixins.html#全局混合)和[插件开发](https://cn.vuejs.org/v2/guide/plugins.html)，给组件添加选项之类的操作才推荐使用全局混合。
