### ISSUE TITLE
router history

### ISSUE THREAD

**Issue by Seven93** [ElderJames/vue-router-storage#14]
带有二级路由的url，使用history模式后，刷新资源加载路径错误，比如：
访问hostUrl/a/b,结果资源原本的路径hostUrl/static/xxx.js 变成了hostUrl/a/static/xxx.js;
请问碰到过这种情况吗？

**Comment by ElderJames** [comment]
资源是import的方式引用或者在入口文件以带/开头的绝对路径引入，应该没问题。

**Comment by Seven93** [comment]
您指的是这个资源吧<script type=text/javascript src=static/js/manifest.b71b16f8d3adbb002ead.js>？这是打包后的index中资源的引入，是指这个src中的路径要带/开头？

**Comment by ElderJames** [comment]
是的，/指定了根目录，没有就是当前目录的相对路径

**Comment by Seven93** [comment]
好的，我先试下，谢谢。

**Comment by Seven93** [comment]
都已绝对路径，可以正常刷新二级路由的页面，不过我打包后Index页面中的资源引入路径都是static/js/xx.js,这个是那个配置导致的呢？而且打包的mainfest.js中的资源引入路径：f.src=n.p+"static/js/"；也不是绝对路径。

**Comment by ElderJames** [comment]
webpack里配置一下，加入 context: __dirname,

**Comment by Seven93** [comment]
ok，谢谢了，我之前已经用另一种方式解决了

**Comment by ElderJames** [comment]
可以说下吗

**Comment by Seven93** [comment]
之前output中的path使用了自己写的工具函数：path: utl.resolve('dist')，这里用的是path.join()方法拼接路径；最后返回了一个相对的路径；然后改成了 path: path.resolve(__dirname, '../../dist')返回绝对路径，打包后的文件就可以正常加载了

**Comment by ElderJames** [comment]
OK，那这个issue就可以关闭了。
