### ISSUE TITLE
建议使用addEventListener,监听popstate事件

### ISSUE THREAD

**Issue by sqchenxiyuan** [ElderJames/vue-router-storage#16]
建议使用addEventListener,监听popstate事件,避免监听函数存在冲突的问题额

https://github.com/ElderJames/vue-router-storage/blob/62d3f05d20781c1793a3ce1a8ccb709d8e2d24dd/src/index.js#L190

**Comment by ElderJames** [comment]
好的，谢谢建议，马上更新一下。
